// components/Layout.tsx
import Head from "next/head";
import React, { ReactNode, useEffect } from "react";
import type { Metadata } from "next";
import Header from "./Header";
import Footer from "./Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Taiwo Ademola</title>
        <meta
          name="description"
          content="Checkout my portolio page"
          key="desc"
        />
        <meta property="og:title" content="Social Title for Cool Page" />
        <meta
          property="og:description"
          content="And a social description for our cool page"
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
      </Head>

      <div className="flex bg-[#190634]">
        <div className="flex-1 flex flex-col max-w-screen-2xl mx-auto px-4">
          <Header />
          <main className="flex-1 p-4 md:p-6">
            {children}
          </main>
          <Footer />

        </div>
      </div>
    </div>
  );
};

export default Layout;
